name: Jeremy
favicon: null
layout_spectrum: 0.864259832073003
typography_spectrum: 0.22727
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#453b0f'
    - '#847710'
    - '#f7f00f'
    - '#e8ac5a'
  brandStrength: 0.3125
  lightness: 0.891856340225786
  saturation: 0.6622670355718583
  rhythmicContrast: 0.6342030074447393
purpose: []
